@startuml

[*] --> CLOSE

CLOSE --> SYN_SENT : appl:send SYN\nsend:SYN

CLOSE --> SYN_RECV : recv:SYN\nsend:SYN+ACK

SYN_SENT --> ESTABLISHED : recv:SYN+ACK\nsend:ACK

SYN_RECV --> ESTABLISHED : recv:ACK\n

ESTABLISHED --> FIN_WAIT_1 : appl:close\nsend:FIN

ESTABLISHED --> CLOSE_WAIT : recv:FIN\nsend:ACK

CLOSE_WAIT --> LAST_ACK : send:FIN

LAST_ACK --> CLOSE : recv:ACK

FIN_WAIT_1 --> FIN_WAIT_2 : recv:ACK

FIN_WAIT_2 --> TIME_WAIT : recv:FIN

FIN_WAIT_1 --> TIME_WAIT : recv:ACK+FIN

TIME_WAIT --> CLOSE

@enduml